Plattegrond klant en Reserveringsscherm
Yor0071/OOSDD-D1 pull request #84
Opened 2024-12-05 22:12 UTC by Ali98-cloud

2024-12-06 00:19 UTC, Yor0071 requested changes

2024-12-06 00:19 UTC, Yor0071 commented on CampingD1/Database/DatabaseQueryHandler.cs
>          Console.WriteLine(query);
Dit kan weg denk ik? is alleen voor debugging neem ik aan

2024-12-06 00:19 UTC, Yor0071 commented on CampingD1/ReservationApp/App.xaml.cs
>                  // MainPage.DisplayAlert("Error", "Failed to connect to the database: " + ex.Message, "OK");
We hebben in de andere applicatie dat de error wel zichtbaar is. Moeten we even bespreken of we dit wel of niet willen toevoegen

2024-12-06 00:19 UTC, Yor0071 commented on CampingD1/ReservationApp/App.xaml.cs
> +            var spotDetails = Database.SelectCampingSpots().FirstOrDefault(s => s.Id == spotId);
spotDetails is alleen het ID neem ik aan? misschien een andere naam geven

2024-12-06 00:19 UTC, Yor0071 commented on CampingD1/ReservationApp/MapScreenCustomer.xaml
je zou eventueel ook de bepaalde elementen die onder elkaar horen kunnen definiëren met een grid.row hierdoor weet je zeker dat alles op een bepaalde rij staat. Maar als dit werkt zoals het is vind ik het prima!

2024-12-06 00:19 UTC, Yor0071 commented on CampingD1/ReservationApp/MapScreenCustomer.xaml.cs
> +
Ik ga mierenneuken en zeggen dat deze enter weg moet haha. verder ziet het er goed uit!

2024-12-06 00:19 UTC, Yor0071 commented on CampingD1/ReservationApp/MauiProgram.cs
> +using CommunityToolkit.Maui; // Zorg ervoor dat je deze alleen eenmaal toevoegt
Waar is dit eigenlijk voor? was het voor bepaalde popups?

2024-12-06 00:19 UTC, Yor0071 commented on CampingD1/ReservationApp/ReservationPopup.cs
> +            var spotDetails = App.Database.SelectCampingSpots().FirstOrDefault(s => s.Id == spotId);
hier ook weer. spotDetails is alleen het ID dus misschien een andere naam geven :)

2024-12-09 10:36 UTC, Ali98-cloud commented on CampingD1/ReservationApp/MapScreenCustomer.xaml
Het werkt zo prima

2024-12-09 10:36 UTC, Ali98-cloud commented on CampingD1/ReservationApp/MapScreenCustomer.xaml.cs
> +
:)

2024-12-09 11:10 UTC, merged